services:
  gateway_service:
    build:
      context: ./gateway_service
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - menu_service

  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:8001"

  menu_service:
    build:
      context: ./menu_service
    ports:
      - "8002:8002"
